all: bubble_sort quicksort insertion_sort
	

bubble_sort: bubble_sort.c
	gcc bubble_sort.c -o bubble_sort

insertion_sort: insertion_sort.c
	gcc insertion_sort.c -o insertion_sort

quicksort: quicksort.c
	gcc quicksort.c -o quicksort
